create table menu_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price numeric not null,
  category text not null,
  image_url text,
  available boolean default true
);

alter table menu_items enable row level security;

-- Allow public read access
create policy "Public Read Access"
on menu_items for select
using (true);

-- Allow authenticated users to insert
create policy "Authenticated Insert Access"
on menu_items for insert
with check (auth.role() = 'authenticated');

-- Allow authenticated users to update
create policy "Authenticated Update Access"
on menu_items for update
using (auth.role() = 'authenticated');

-- Allow authenticated users to delete
create policy "Authenticated Delete Access"
on menu_items for delete
using (auth.role() = 'authenticated');
